server {
  listen 80;
  listen [::]:80;

  access_log off;
  #access_log /var/log/nginx/server2.openrhynn.net.log;
  #error_log /var/log/nginx/server2.openrhynn.net-error.log;

  server_name server2.openrhynn.net;

  location / {
    proxy_pass http://127.0.0.1:8181;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
